### ISSUE TITLE
consider not using es6 (=>) syntax on line 16

### ISSUE THREAD

**Issue by sylhero** [shirohana/native-require#1]
webpack UglifyJs doesn't like the es6 syntax and it breaks the build

**Comment by shirohana** [comment]
I see, fix it soon :)

**Comment by sylhero** [comment]
@shirohana tried to make a pull request but it seems you disabled that ;)

**Comment by sylhero** [comment]
@shirohana also a question the filepath has to be absolute path?
`let filename = join(__dirname, name)`

**Comment by shirohana** [comment]
Ehh? I didn't modify any options since I create this repo :(

Wait me a minute.

**Comment by shirohana** [comment]
Maybe you should fork this project before you create a pull request?

**Comment by shirohana** [comment]
Because of this module is for resolving require paths, the require paths should resolving from the `cwd()` where you require it (or provide it as a option yourself). There's no needed to leave a filename or parent since it is a external module.

By the way, you can print `module` from your node CLI, I make this module just like this.
![2017-08-16 3 55 50](https://user-images.githubusercontent.com/11359892/29333617-04309912-8237-11e7-87bd-a067847ef4a0.png)

**Comment by sylhero** [comment]
@shirohana thanks for your response. I have another question regarding `webpack-node-externals`. What's the difference if I'm not using it?

**Comment by shirohana** [comment]
In most case you can install `native-require` as a dev-dependency, but only if you using webpack to write a bundler module, you should install it as a dependency.

Sorry for that I replied so late, I was trying to write an example to explain it, but it took too many time for replying. I'll update some examples after I fix the `arrow-function` syntax issue.

In my memories, I wrote this module because I got some problems when writing a bundler module.

**Comment by sylhero** [comment]
@shirohana no, you did a great job! :)

**Comment by shirohana** [comment]
Published (https://github.com/shirohana/native-require/commit/e396d27a29b8818c78708e78febc77496eac02e6)! also update README and API.

Sorry for that I'll update explanation about difference between `--save` and `--save-dev`. It already 5:24AM here (˘̩̩̩ ω ˘̩ƪ)

**Comment by shirohana** [comment]
Hello,
Sorry for replying so late, I have something important in the front.
I think the most different between `--save` and `--save-dev` is the things I told above.

    Use `--save-dev` at almost time, but only use `webpack` to build a bundler module.

To use `webpack` as a bundler core, you may `--save webpack` and `--save webpack-node-externals or --save-dev webpack-node-externals`. Anyway, if you have `webpack-node-externals` in your dependency, you should `--save native-require`. Otherwise, just `--save-dev`

**Comment by shirohana** [comment]
Maybe I should modify `README.me`, thanks for your question :)
